const $=id=>document.getElementById(id);
const RULES=[
  ['hook','0–3 秒直接給痛點、反差或好奇點'],
  ['story','用一個自己的真實故事，不寫空泛說教'],
  ['turn','故事後給「原來是這樣」的反轉'],
  ['action','只給 1 個或 3 個能立刻做的方法'],
  ['share','結尾提供值得轉給朋友的理由'],
  ['voice','語氣直接、有趣，避免太溫柔的療癒感'],
  ['business','兼顧 IP 與變現，讓觀眾知道你能幫誰']
];
const REJECT=['太雞湯','太空泛','不像我的口吻','缺真實故事','沒有變現方向','開頭太慢','CTA 太硬'];
let prefs=Object.fromEntries(RULES.map(([k])=>[k,true])),rejects={},current=null,videoUrl=null,imageUrls=[];
const safe=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const rate=(a,b)=>a!=null&&b>0?(a/b*100).toFixed(1)+'%':'未辨識';
const status=s=>{$('status').textContent=s;$('status').classList.add('show')};
const dbPromise=new Promise((resolve,reject)=>{const req=indexedDB.open('video-insight',1);req.onupgradeneeded=()=>{const db=req.result;db.createObjectStore('records',{keyPath:'id'});db.createObjectStore('settings')};req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)});
async function store(name,mode,fn){const db=await dbPromise;return new Promise((resolve,reject)=>{const tx=db.transaction(name,mode);let value;try{value=fn(tx.objectStore(name))}catch(e){reject(e);return}tx.oncomplete=()=>resolve(value);tx.onerror=()=>reject(tx.error)})}
async function allRecords(){const db=await dbPromise;return new Promise((resolve,reject)=>{const q=db.transaction('records').objectStore('records').getAll();q.onsuccess=()=>resolve(q.result.sort((a,b)=>b.createdAt-a.createdAt));q.onerror=()=>reject(q.error)})}
async function getSetting(key){const db=await dbPromise;return new Promise(resolve=>{const q=db.transaction('settings').objectStore('settings').get(key);q.onsuccess=()=>resolve(q.result);q.onerror=()=>resolve(null)})}
async function saveSettings(){await store('settings','readwrite',s=>s.put({prefs,rejects},'profile'))}
function renderRules(){ $('rules').innerHTML=RULES.map(([k,label])=>`<button class="chip ${prefs[k]?'on':''}" data-rule="${k}" aria-pressed="${!!prefs[k]}">${safe(label)}</button>`).join('');$('learned').innerHTML=Object.entries(rejects).filter(([,n])=>n>0).map(([label,n])=>`<span class="chip bad">${safe(label)} · ${n} 次</span>`).join('')||'<p class="small">還沒有回饋。分析後可點選不符合的建議。</p>'}
$('rules').addEventListener('click',async e=>{const k=e.target.closest('[data-rule]')?.dataset.rule;if(!k)return;prefs[k]=!prefs[k];renderRules();await saveSettings()});
function switchView(view){for(const name of ['New','History','Rules']){$('tab'+name).classList.toggle('active',name===view);$(name.toLowerCase()+'View').classList.toggle('hidden',name!==view)}if(view==='History')renderHistory();if(view==='Rules')renderRules()}
for(const name of ['New','History','Rules'])$('tab'+name).onclick=()=>switchView(name);
$('images').onchange=e=>{imageUrls.forEach(URL.revokeObjectURL);const files=[...e.target.files];imageUrls=files.map(URL.createObjectURL);$('shots').replaceChildren(...imageUrls.map(url=>{const im=document.createElement('img');im.src=url;im.alt='後台數據截圖';return im}));$('imageNames').textContent=files.map(f=>f.name).join('、')};
$('videoFile').onchange=e=>{if(videoUrl)URL.revokeObjectURL(videoUrl);const f=e.target.files[0];if(!f)return;videoUrl=URL.createObjectURL(f);$('preview').src=videoUrl;$('preview').style.display='block';$('videoName').textContent=f.name+' · '+(f.size/1048576).toFixed(1)+' MB'};
function norm(s){return String(s).normalize('NFKC').replace(/[，]/g,',').replace(/[：]/g,':')}
function numberToken(s,kind){const text=norm(s);if(kind==='time'){const t=text.match(/(\d{1,2}:)?\d{1,2}:\d{2}/);if(t){const p=t[0].split(':').map(Number);return p.reduce((a,v)=>a*60+v,0)}const sec=text.match(/(\d+(?:\.\d+)?)\s*(?:秒|sec(?:onds?)?)/i);return sec?+sec[1]:null}if(kind==='percent'){const m=text.match(/(\d+(?:\.\d+)?)\s*%/);return m?+m[1]:null}const m=text.match(/(?<!\d)(\d{1,3}(?:,\d{3})+|\d+(?:\.\d+)?)\s*([萬万kKmM])?/);if(!m)return null;const x=+m[1].replaceAll(',','');return x*({'萬':10000,'万':10000,k:1000,K:1000,m:1000000,M:1000000}[m[2]]||1)}
const LABELS={
 views:/觀看(?:次數|數)?|播放(?:次數|數)?|views?|plays?/i,
 shares:/分享(?:次數|數)?|轉發(?:次數|數)?|shares?|reposts?/i,
 saves:/收藏(?:次數|數)?|儲存(?:次數|數)?|saves?/i,
 likes:/按讚(?:次數|數)?|喜歡(?:次數|數)?|likes?/i,
 comments:/留言(?:次數|數)?|評論(?:次數|數)?|comments?/i,
 average:/平均(?:觀看|播放)(?:時間|時長|秒數)?|average\s*watch\s*time/i,
 retention:/前\s*3\s*秒(?:留存|觀看)|3[- ]?second\s*(?:retention|view)/i
};
function extractMetrics(text){const lines=norm(text).split(/\n/).map(s=>s.trim()).filter(Boolean),out={};for(const [key,re] of Object.entries(LABELS)){const kind=key==='average'?'time':key==='retention'?'percent':'count';let candidates=[];for(let i=0;i<lines.length;i++){const m=lines[i].match(re);if(!m)continue;let same=lines[i].replace(m[0],'').replace(/^[\s:：-]+/,'');let v=numberToken(same,kind);if(v!==null)candidates.push({value:v,confidence:'較高',line:lines[i]});for(const j of [i+1,i-1]){if(j<0||j>=lines.length||Object.values(LABELS).some(x=>x.test(lines[j])))continue;v=numberToken(lines[j],kind);if(v!==null)candidates.push({value:v,confidence:'需核對',line:lines[i]+' / '+lines[j]})}}out[key]=candidates[0]||null}return out}
function metricsValues(m){return Object.fromEntries(Object.entries(m).map(([k,v])=>[k,v?.value??null]))}
function screenshotData(file){return new Promise((resolve,reject)=>{const url=URL.createObjectURL(file),im=new Image();im.onload=()=>{const scale=Math.min(1,1000/im.width),c=document.createElement('canvas');c.width=Math.max(1,Math.round(im.width*scale));c.height=Math.max(1,Math.round(im.height*scale));c.getContext('2d').drawImage(im,0,0,c.width,c.height);URL.revokeObjectURL(url);resolve(c.toDataURL('image/jpeg',.68))};im.onerror=()=>{URL.revokeObjectURL(url);reject(new Error('截圖無法開啟'))};im.src=url})}
async function waitMetadata(video){if(Number.isFinite(video.duration)&&video.duration>0)return video.duration;return new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(new Error('影片無法讀取片長')),12000);video.addEventListener('loadedmetadata',()=>{clearTimeout(timer);resolve(video.duration)},{once:true});video.addEventListener('error',()=>{clearTimeout(timer);reject(new Error('影片格式無法讀取'))},{once:true})})}
async function frameAt(video,time){return new Promise((resolve,reject)=>{const timer=setTimeout(()=>{cleanup();reject(new Error('影片取樣逾時'))},9000);const cleanup=()=>{clearTimeout(timer);video.removeEventListener('seeked',done);video.removeEventListener('error',bad)};const done=()=>{cleanup();const c=document.createElement('canvas'),scale=Math.min(1,720/video.videoWidth);c.width=Math.max(1,Math.round(video.videoWidth*scale));c.height=Math.max(1,Math.round(video.videoHeight*scale));c.getContext('2d',{willReadFrequently:true}).drawImage(video,0,0,c.width,c.height);resolve(c)};const bad=()=>{cleanup();reject(new Error('影片畫面無法擷取'))};video.addEventListener('seeked',done,{once:true});video.addEventListener('error',bad,{once:true});video.currentTime=time})}
function frameDifference(a,b){const c=document.createElement('canvas');c.width=64;c.height=36;const ctx=c.getContext('2d',{willReadFrequently:true});ctx.drawImage(a,0,0,64,36);const x=ctx.getImageData(0,0,64,36).data;ctx.drawImage(b,0,0,64,36);const y=ctx.getImageData(0,0,64,36).data;let sum=0;for(let i=0;i<x.length;i+=4)sum+=Math.abs(x[i]-y[i])+Math.abs(x[i+1]-y[i+1])+Math.abs(x[i+2]-y[i+2]);return sum/(64*36*3)}
function uniqueTimes(duration){return [...new Set([.2,Math.min(2.5,duration*.12),Math.min(7,duration*.3),duration*.55,Math.max(.2,duration-2)].map(t=>Math.min(Math.max(0,t),Math.max(0,duration-.05)).toFixed(1)))].map(Number)}
function cleanCaption(s){return norm(s).split('\n').map(x=>x.trim()).filter(x=>x.length>=4&&!/^\d+[.,:]?\d*$/.test(x)).slice(0,3).join(' ').slice(0,95)}
async function videoAnalysis(worker){const video=$('preview'),duration=await waitMetadata(video),frames=[],captions=[];if(!Number.isFinite(duration)||duration<=0)throw new Error('影片時長無法讀取');const times=uniqueTimes(duration).slice(0,5);for(let i=0;i<times.length;i++){status(`讀取影片畫面 ${i+1}/${times.length}…`);try{const frame=await frameAt(video,times[i]);frames.push(frame);const {data}=await worker.recognize(frame);captions.push({at:times[i],text:cleanCaption(data.text)})}catch(e){captions.push({at:times[i],text:''})}}const changes=frames.length>1?frames.slice(1).map((f,i)=>frameDifference(frames[i],f)):[];return {duration,captionSamples:captions,openingChange:changes[0]??null}}
function buildResult(m,video,raw,history=[]){const v=metricsValues(m),share=rate(v.shares,v.views),save=rate(v.saves,v.views),watch=v.average!=null&&video?.duration?Math.round(v.average/video.duration*100):null,caption=video?.captionSamples.find(x=>x.text)?.text||'',opening=video?.captionSamples.slice(0,2).find(x=>x.text)?.text||'';let flags=[],advice=[];
 if(v.views==null)flags.push(['觀看數未辨識','請換一張文字清楚、包含觀看數的後台截圖後重新分析。']);
 if(v.shares!=null&&v.views>0)flags.push(['分享率 '+share,'這是分享次數除以觀看數；和你自己的其他影片比較才更有意義。']);
 if(v.average!=null&&video?.duration)flags.push(['平均觀看約為片長 '+watch+'%','平均值不能定位掉點；有留存曲線截圖時仍須看曲線。']);
 if(v.retention!=null)flags.push(['前 3 秒留存 '+v.retention+'%','開頭強弱要和你過去影片比較，不只看單支。']);
 const prior=history.map(r=>({views:r.metrics?.views?.value,shares:r.metrics?.shares?.value})).filter(x=>x.views>0&&x.shares!=null).map(x=>x.shares/x.views).sort((a,b)=>a-b);
 if(prior.length>=3&&v.views>0&&v.shares!=null){const baseline=prior[Math.floor(prior.length/2)];flags.push(['和你過去影片比較',`目前分享率 ${share}；你先前 ${prior.length} 支影片的中位數約 ${(baseline*100).toFixed(1)}%。${v.shares/v.views<baseline?' 這支可優先測試更明確的轉發情境。':' 這支的分享率高於你的過往中位數，可保留有效段落。'}`])}
 if(Object.values(m).some(x=>x?.confidence==='需核對'))flags.push(['部分數字需核對','截圖的標籤與數字不在同一行，可能配對錯誤；請對照下方辨識文字。']);
 if(prefs.hook)advice.push(['0–3 秒｜先給理由',opening?`畫面辨識到「${opening}」。檢查第一格畫面與第一句是否直接指出痛點或反差。`:'前段沒有辨識到可讀字幕。第一格先放一句具體問題或反差，別從打招呼開始。']);
 if(video?.openingChange!=null&&video.openingChange<9)advice.push(['開頭畫面變化較小','前兩個取樣畫面相近。可檢查前 3 秒是否需要更早切到關鍵畫面；這不能直接判定觀眾流失。']);
 if(prefs.story)advice.push(['中段｜個人故事','只留一個真實片段：你當時怎麼做、遇到什麼、後來發現什麼。']);
 if(prefs.turn)advice.push(['後段｜反轉','給一個「我原本以為…後來發現…」的觀點轉折，避免重複開頭。']);
 if(prefs.action)advice.push(['方法｜立刻能做','選 1 個動作；如果是教學類，再拆成 3 個短步驟。']);
 if(prefs.share)advice.push(['結尾｜分享情境',rejects['CTA 太硬']?'用一句觀眾會想傳給朋友的總結收尾，不直接要求轉發。':'讓觀眾知道這支適合傳給哪一種朋友。']);
 if(prefs.business)advice.push(['IP 與變現','讓觀眾看出你擅長解決的問題，先建立信任，再自然承接產品或服務。']);
 if(rejects['開頭太慢'])advice.unshift(['你曾回饋：開頭太慢','下次把背景和自我介紹移到痛點之後，第一句直接進事件。']);
 if(rejects['太空泛'])advice.push(['你曾回饋：太空泛','每一段都換成可拍的畫面、具體動作或一句真實原話；沒有素材就標記待補，不編故事。']);
 if(rejects['缺真實故事'])advice.push(['你曾回饋：缺真實故事','至少留一個你親身遇過的場景與當時反應，別只講道理。']);
 if(rejects['沒有變現方向'])advice.push(['你曾回饋：沒有變現方向','讓結尾接到你能提供的內容、服務或產品，但不要硬塞購買口號。']);
 const tone=rejects['太雞湯']||rejects['不像我的口吻']||prefs.voice?'直接講具體經歷，不用溫柔鼓勵句。':'保持自然口吻。';
 const hook=opening?`把畫面上的「${opening}」改成對觀眾說的問題或反差；如果原句已夠直接就保留。`:'第一句先點出觀眾正在遇到的具體問題（影片前段沒有可辨識字幕）。';
 const script=[prefs.hook?`【0–3 秒｜開頭】\n${hook}`:null,prefs.story?'【3–15 秒｜你的真實故事】\n用一個具體時刻：發生什麼事 → 你當下的反應。影片沒有完整口播逐字稿，請用你的實際經驗補這段。':null,prefs.turn?'【轉折】\n「我原本以為＿＿，後來發現＿＿。」把真正的觀察填進去。':null,prefs.action?'【方法】\n只留一個現在就能做的動作，說清楚第一步。':null,prefs.share?'【結尾】\n用一句讓朋友想互傳的觀察收尾，再問一個好回答的問題。':null,`【語氣】\n${tone}`,caption?`【畫面可辨識文字】\n${caption}`:'【提醒】\n未讀到足夠字幕，無法判斷完整口播的論點與用字。'].filter(Boolean).join('\n\n');
 return {metrics:m,video,raw,flags,advice,script,share,save};
}
function renderResult(r){current=r;$('results').classList.add('show');$('stats').innerHTML=[['觀看數',r.metrics.views?.value],['分享率',r.share],['收藏率',r.save],['平均觀看',r.metrics.average?.value!=null?r.metrics.average.value+' 秒':null],['前 3 秒留存',r.metrics.retention?.value!=null?r.metrics.retention.value+'%':null],['片長',r.video?.duration?r.video.duration.toFixed(1)+' 秒':null]].map(([k,v])=>`<div class="stat"><small>${k}</small><strong>${safe(v??'未辨識')}</strong></div>`).join('');$('flags').innerHTML=r.flags.map(([h,b])=>`<div class="flag"><b>${safe(h)}</b>${safe(b)}</div>`).join('');$('advice').innerHTML=r.advice.map(([h,b])=>`<div class="flag"><b>${safe(h)}</b>${safe(b)}</div>`).join('');$('script').textContent=r.script;$('raw').textContent=r.raw||'未辨識到文字';$('feedback').innerHTML=REJECT.map(x=>`<button class="chip" data-reject="${safe(x)}">${safe(x)}</button>`).join('');$('results').scrollIntoView({behavior:'smooth',block:'start'})}
$('feedback').onclick=async e=>{const b=e.target.closest('[data-reject]');if(!b||!current)return;const label=b.dataset.reject;if(b.classList.contains('on'))return;b.classList.add('on','bad');rejects[label]=(rejects[label]||0)+1;await saveSettings();if(current.id){current.feedback=[...(current.feedback||[]),label];await store('records','readwrite',s=>s.put(current))}renderRules()};
$('copy').onclick=async()=>{try{await navigator.clipboard.writeText($('script').textContent);$('copy').textContent='已複製';setTimeout(()=>$('copy').textContent='複製建議',1800)}catch(e){alert('請長按建議文字複製')}};
$('save').onclick=async()=>{if(!current)return;try{if(!current.id){current.id=crypto.randomUUID();current.createdAt=Date.now()}await store('records','readwrite',s=>s.put(current));$('save').textContent='已儲存'}catch(e){status('儲存失敗，請先下載備份或清出裝置空間。')}};
$('analyze').onclick=async()=>{const images=[...$('images').files],videoFile=$('videoFile').files[0];if(!images.length){status('先選至少一張後台數據截圖。');return}if(!window.Tesseract){status('文字辨識元件未載入，請確認網路連線後重新開啟。');return}const button=$('analyze');button.disabled=true;let worker;try{status('首次使用正在下載繁體中文辨識元件，請稍候…');worker=await Tesseract.createWorker(['chi_tra','eng'],1,{logger:m=>{if(m.status==='recognizing text')status(`正在辨識文字 ${Math.round((m.progress||0)*100)}%…`)}});const texts=[],thumbs=[];for(let i=0;i<images.length;i++){status(`辨識後台截圖 ${i+1}/${images.length}…`);const result=await worker.recognize(images[i]);texts.push(result.data.text);if(i<5)thumbs.push(await screenshotData(images[i]))}const raw=texts.join('\n\n--- 下一張截圖 ---\n\n'),metrics=extractMetrics(raw);let video=null;if(videoFile){try{video=await videoAnalysis(worker);video.name=videoFile.name}catch(err){status('影片畫面暫時無法分析，會先用截圖完成數據診斷。')}}const previous=await allRecords().catch(()=>[]),result=buildResult(metrics,video,raw,previous);result.images=thumbs;result.names=images.map(f=>f.name);result.id=crypto.randomUUID();result.createdAt=Date.now();renderResult(result);try{await store('records','readwrite',s=>s.put(result));$('save').textContent='已自動儲存';status('分析完成，已存入歷史紀錄。')}catch(e){status('分析完成，但本機儲存失敗；可複製建議，並確認裝置空間。')}}catch(e){status('辨識未完成：'+(e?.message||'請換一張清楚的截圖，並確認網路連線。'))}finally{button.disabled=false;if(worker)await worker.terminate().catch(()=>{})}};
async function renderHistory(){try{const rows=await allRecords();$('history').innerHTML=rows.map(r=>`<button class="record" data-id="${safe(r.id)}"><b>${new Date(r.createdAt).toLocaleString('zh-TW')} · ${safe(r.video?.name||r.names?.[0]||'後台截圖')}</b><small>觀看 ${safe(r.metrics.views?.value??'未辨識')} · 分享率 ${safe(r.share)} · ${(r.feedback||[]).length} 項回饋</small></button>`).join('')||'<p class="small">還沒有紀錄。完成一次分析後會出現在這裡。</p>'}catch(e){$('history').textContent='無法讀取本機紀錄'}}
$('history').onclick=async e=>{const id=e.target.closest('[data-id]')?.dataset.id;if(!id)return;const db=await dbPromise;const r=await new Promise(resolve=>{const q=db.transaction('records').objectStore('records').get(id);q.onsuccess=()=>resolve(q.result)});if(r){switchView('New');renderResult(r);$('save').textContent='已儲存'}};
$('export').onclick=async()=>{try{const payload={schema:1,exportedAt:new Date().toISOString(),records:await allRecords(),profile:{prefs,rejects}},blob=new Blob([JSON.stringify(payload)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='影像拆解室-備份-'+new Date().toISOString().slice(0,10)+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),30000)}catch(e){alert('備份失敗，請重試')}};
$('import').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{const data=JSON.parse(await f.text());if(data.schema!==1||!Array.isArray(data.records)||data.records.some(r=>!r.id||!r.createdAt||!r.metrics))throw Error('格式不正確');for(const r of data.records)await store('records','readwrite',s=>s.put(r));if(data.profile?.prefs){prefs={...prefs,...data.profile.prefs};rejects=data.profile.rejects||rejects;await saveSettings();renderRules()}await renderHistory();alert(`已匯入 ${data.records.length} 筆紀錄`)}catch(err){alert('備份檔無法匯入：'+err.message)}e.target.value=''};
(async()=>{try{const saved=await getSetting('profile');if(saved){prefs={...prefs,...saved.prefs};rejects=saved.rejects||{}}if(navigator.storage?.persist)navigator.storage.persist().catch(()=>{});renderRules()}catch(e){status('本機儲存不可用；仍可分析並複製建議。')}})();
